options:
  fsid:
    type: string
    default:
    description: |
      fsid of the ceph cluster. To generate a suitable value use `uuid`
      .
      This configuration element is mandatory and the service will fail on
      install if it is not provided.
  monitor-hosts:
    type: string
    default:
    description: |
      Space separated list of existing monitor hosts, in the format
      {IP / Hostname}:{port} {IP / Hostname}:{port}
  admin-key:
    type: string
    default:
    description: |
      Admin cephx key for existing Ceph cluster
  mon-key:
    type: string
    default:
    description: |
      Monitor cephx key
  source:
    type: string
    default:
    description: |
      Optional configuration to support use of additional sources such as:

        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main

      The last option should be used in conjunction with the key configuration
      option.

      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise but is provided in the Ubuntu cloud archive.
  key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
