options:
  osd-devices:
    type: string
    default: /dev/vdb
    description: |
      The devices to format and set up as osd volumes.
      .
      These devices are the range of devices that will be checked for and
      used across all service units.
  ephemeral-unmount:
    type: string
    description: |
      Cloud instances provider ephermeral storage which is normally mounted
      on /mnt.
      .
      Providing this option will force an unmount of the ephemeral device
      so that it can be used as a OSD storage device.  This is useful for
      testing purposes (cloud deployment is not a typical use case).
  source:
    type: string
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:folsom-proposed
        - http://my.archive.com/ubuntu main
      .
      The last option should be used in conjunction with the key configuration
      option.
      .
      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise.
  key:
    type: string
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
