options:
  osd-devices:
    type: string
    default: /dev/vdb
    description: |
      The devices to format and set up as osd volumes.
      .
      These devices are the range of devices that will be checked for and
      used across all service units.
      .
      For ceph >= 0.56.6 these can also be directories instead of devices - the
      charm assumes anything not starting with /dev is a directory instead.
  osd-journal:
    type: string
    description: |
      The device to use as a shared journal drive for all OSD's.  By default
      no journal device will be used.
      .
      Only supported with ceph >= 0.48.3.
  osd-journal-size:
    type: int
    default: 1024
    description: |
      Ceph osd journal size. The journal size should be at least twice the
      product of the expected drive speed multiplied by filestore max sync
      interval. However, the most common practice is to partition the journal
      drive (often an SSD), and mount it such that Ceph uses the entire
      partition for the journal.
      .
      Only supported with ceph >= 0.48.3.
  osd-format:
    type: string
    default: xfs
    description: |
      Format of filesystem to use for OSD devices; supported formats include:
      .
        xfs (Default >= 0.48.3)
        ext4 (Only option < 0.48.3)
        btrfs (experimental and not recommended)
      .
      Only supported with ceph >= 0.48.3.
  osd-reformat:
    type: string
    description: |
      By default, the charm will not re-format a device that already looks
      as if it might be an OSD device.  This is a safeguard to try to
      prevent data loss.
      .
      Specifying this option (any value) forces a reformat of any OSD devices
      found which are not already mounted.
  ephemeral-unmount:
    type: string
    description: |
      Cloud instances provider ephermeral storage which is normally mounted
      on /mnt.
      .
      Providing this option will force an unmount of the ephemeral device
      so that it can be used as a OSD storage device.  This is useful for
      testing purposes (cloud deployment is not a typical use case).
  source:
    type: string
    default: cloud:precise-updates/folsom
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:precise-proposed/folsom
        - http://my.archive.com/ubuntu main
      .
      The last option should be used in conjunction with the key configuration
      option.
      .
      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise but is provided in the Ubuntu cloud archive.
  key:
    type: string
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
