options:
  fsid:
    type: string
    description: |
      fsid of our cluster
  osd-devices:
    type: string
    default: /dev/sdb /dev/sdc /dev/sdd /dev/sde
    description: |
      the devices to format and set up as osd volumes
  monitor-count:
    type: int
    default: 3
    description: |
      how many nodes to wait for before trying to create the monitor cluster
      this number needs to be odd, and more than three is a waste except for
      very large clusters
  monitor-secret:
    type: string
    description: |
      this value will become the "mon." key
      to generate a suitable value, use
      ceph-authtool /dev/stdout --name=mon. --gen-key
  source:
    type: string
    default: ppa:ceph-ubuntu/dev
